services:
  # gr-dir:
  #   image: busybox
  #   entrypoint: cat /file
  #   volumes:
  #     - ./configs/${PORTAINER_EDGE_GROUP}/file:/file

  gr-file:
    image: busybox
    entrypoint: cat /file
    volumes:
      - ./configs/${PORTAINER_EDGE_GROUP}:/file

  # id-dir:
  #   image: busybox
  #   entrypoint: cat /file
  #   volumes:
  #     - ./configs/${PORTAINER_EDGE_ID}/file:/file

  id-file:
    image: busybox
    entrypoint: cat /file
    volumes:
      - ./configs/${PORTAINER_EDGE_ID}:/file